# This workflow will install Python dependencies, run tests and lint with several versions of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Continuous Integration

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

env:
  SERVICE_NAME: actrac
  RUFF_VERSION: '0.8.2'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [10, 11, 12, 13, 14]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.${{ matrix.python-version }}'
        cache: 'poetry'

    - name: Install poetry
      run: pipx install poetry==1.8.3
      shell: bash

    - name: Set up Ruff and lint
      uses: astral-sh/ruff-action@v3
      with:
        version: ${{ env.RUFF_VERSION }}
        src: ./actrac

    - name: Run unit tests (e.g., pytest)
      # Ensure you have pytest as a dev dependency in pyproject.toml
      run: poetry run pytest --log-cli-level DEBUG -cov-config=.coveragerc --cov --cov-append --cov-report xml:cov.xml --cov-report term --junitxml=result.xml -s test/unit/
